server:
  undertow:
    threads:
      io:
      worker:
  port: 2333

spring:
#  elasticsearch:
#    rest:
#      uris: http://localhost:9200
#      username: elastic
#      password: gigHO24kdSN=M=8h3oSU
  application:
    name: moon-consumer
  thymeleaf:
    prefix: classpath:/views/
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moon?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    druid:
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存时间
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开 PSCache，并且指定每个连接上 PSCache 的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20

  # Sharding-JDBC的配置
#  shardingsphere:
#    datasource:
#      # 数据源，这里配置两个，分别是ds1，ds2
#      names: ds1,ds2
#      # ds1的配置信息,product_db1
#      ds1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/product_db?useUnicode=true&characterEncoding=utf-8
#        username: root
#        password: Nov2014
#      # ds2的配置信息，shop_db
#      ds2:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/shop_db?useUnicode=true&characterEncoding=utf-8
#        username: root
#        password: Nov2014

#    # 分片的配置
#    sharding:
#      # 表的分片策略
#      tables:
#        t_user:
#          actualDataNodes: default.t_user_${0..7}
#          tableStrategy:
#            inline:
#              shardingColumn: id
#              algorithmExpression: t_user_${(id>>22) % 8}
#        bindingTables:
#          - t_user

#  redis:
#    port: 7671
#    host: minqiwudian.xyz
#    database: 0
#    timeout: 2s

logging:
  level:
    org.springframework.web: INFO
    cn.minqi: DEBUG
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36})  - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file: logs/application.log

config:
  user: eb3dcda7e8ada79c123d74ea5a8c02ac
  baseEncodeStr: seven
  splitStr: "&"

# swagger API文档
swagger:
  enabled: true
  title: API文档
  version: 1.0.0
  base-package: cn.minqi.consumer.web
