server:
  port: 2333
  undertow:
    io-threads: 2
    worker-threads: 200

spring:
  application:
    name: moon-consumer
  thymeleaf:
    prefix: classpath:/views/
    cache: false

logging:
  level:
    org.springframework.web: INFO
    cn.minqi: DEBUG
  pattern:
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{36})  - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: logs/application.log

config:
  user: eb3dcda7e8ada79c123d74ea5a8c02ac
  baseEncodeStr: seven
  splitStr: "&"

# swagger API文档
swagger:
  enabled: true
  title: API文档
  version: 1.0.0
  base-package: cn.minqi.consumer.web
